-- 1. Tambah kolom email ke public.profile jika belum ada
ALTER TABLE public.profile ADD COLUMN IF NOT EXISTS email TEXT;

-- 2. Membuat tabel public.last_smoke jika belum ada
CREATE TABLE IF NOT EXISTS public.last_smoke (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id UUID NOT NULL,
    last_smoke TIMESTAMP WITH TIME ZONE NOT NULL,
    
    -- Menghubungkan profile_id dengan foreign key ke public.profile(id)
    CONSTRAINT fk_profile FOREIGN KEY (profile_id) REFERENCES public.profile(id) ON DELETE CASCADE
);

-- Mengaktifkan Row Level Security (RLS)
ALTER TABLE public.profile ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.last_smoke ENABLE ROW LEVEL SECURITY;

-- Kebijakan RLS untuk public.profile
DROP POLICY IF EXISTS "Allow public read access on profiles" ON public.profile;
CREATE POLICY "Allow public read access on profiles" 
ON public.profile FOR SELECT 
USING (true);

-- Kebijakan RLS untuk public.last_smoke
DROP POLICY IF EXISTS "Pengguna dapat melihat last_smoke milik sendiri" ON public.last_smoke;
CREATE POLICY "Pengguna dapat melihat last_smoke milik sendiri" 
ON public.last_smoke FOR SELECT 
USING (auth.uid() = profile_id);

DROP POLICY IF EXISTS "Pengguna dapat menambahkan last_smoke milik sendiri" ON public.last_smoke;
CREATE POLICY "Pengguna dapat menambahkan last_smoke milik sendiri" 
ON public.last_smoke FOR INSERT 
WITH CHECK (auth.uid() = profile_id);

DROP POLICY IF EXISTS "Pengguna dapat memperbarui last_smoke milik sendiri" ON public.last_smoke;
CREATE POLICY "Pengguna dapat memperbarui last_smoke milik sendiri" 
ON public.last_smoke FOR UPDATE 
USING (auth.uid() = profile_id);

DROP POLICY IF EXISTS "Pengguna dapat menghapus last_smoke milik sendiri" ON public.last_smoke;
CREATE POLICY "Pengguna dapat menghapus last_smoke milik sendiri" 
ON public.last_smoke FOR DELETE 
USING (auth.uid() = profile_id);

-- Memastikan role anon dan authenticated memiliki hak akses SELECT pada profile
GRANT SELECT ON public.profile TO anon, authenticated;


-- 3. Membuat atau memperbarui fungsi trigger untuk menyalin data saat user baru daftar
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    -- Masukkan ke tabel public.profile terlebih dahulu karena foreign key constraint
    INSERT INTO public.profile (id, full_name, username, email)
    VALUES (
        NEW.id,
        COALESCE(
            NEW.raw_user_meta_data->>'full_name', 
            NEW.raw_user_meta_data->>'fullName', 
            NEW.raw_user_meta_data->>'name', 
            NEW.raw_user_meta_data->>'nama'
        ),
        NEW.raw_user_meta_data->>'username',
        NEW.email -- Menyimpan email ke tabel profil agar bisa digunakan untuk login berbasis username
    );

    -- Masukkan ke tabel public.last_smoke setelah data profile terbuat
    IF NEW.raw_user_meta_data->>'last_smoke' IS NOT NULL THEN
        INSERT INTO public.last_smoke (profile_id, last_smoke)
        VALUES (
            NEW.id,
            (NEW.raw_user_meta_data->>'last_smoke')::TIMESTAMP WITH TIME ZONE
        );
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- 4. Membuat trigger di auth.users (jika belum ada)
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW 
    EXECUTE FUNCTION public.handle_new_user();
